version: '3'

services:
  frontend:
    image: airline-frontend:latest
    build: ./frontend
    container_name: frontend
    stdin_open: true
    ports: 
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
    networks:
      - team5-airline
  
  backend:
    image: airline-backend:latest
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    ports:
      - "4000:4000"
    networks:
      - team5-airline

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - team5-airline
    volumes:
      - mongo-data:/data/db

volumes: 
  mongo-data:

networks:
  team5-airline:
    driver: bridge
